LESSON 2.1
Natasha-eng/webix2 pull request #1
Opened 2024-09-12 09:40 UTC by Natasha-eng

2024-09-12 22:07 UTC, HelgaListopad requested changes

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +            butt.attachEvent("onItemClick", function (id) {
Здесь и в `save`:
Если ты хочешь сократить слово button, лучше используй `btn` , иначе получается не совсем то, что нужно показывать в коде (:

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +                            id: "cancel",
Не стоит задавать глобальные `id` внутри компонента - с ними его невозможно будет переиспользовать.
Они не изолируются внутри формы, и если использовать два компонента customForm, ты получишь кнопки с неуникальными ID (debug-версия библиотеки покажет об этом предупреждение).

Для `queryView` ты можешь использовать любые свойства, в том числе и кастомные. 
Т.е. в конфигурации кнопок можно смело написать своё свойство: `$innerName`, `$customId` - что угодно, и потом искать кнопку по нему.

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +            this.$ready.push(this.save)
1. cancel/save подразумевает само действие (сохранение или отмену). Любые методы лучше называть так, чтобы было понятно, что они делают. У тебя они задают действие на кнопку.
2. Можно проще - почему бы не задать `click` или `on: { onItemClick(){} }` сразу в конфигурацию кнопок?

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +    autoconfig: true,
У компонента list нет `autoconfig`

2024-09-12 22:07 UTC, HelgaListopad commented on styles.css
> +    ;
Лишний semicolon

2024-09-12 22:07 UTC, HelgaListopad commented on styles.css
> +    ;
Лишний semicolon

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +            const saveaction = this.config.saveAction;
В задании не очевидно, но я бы предложила разделить методы
По клику Save => saveAction
По клику Cancel => cancelAction

Использовать один метод, передавая туда информацию о том, на какую кнопку кликнули - в целом ок, но тогда общий метод не должен называться saveAction

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +            const saveaction = this.config.saveAction;
Помимо этого, из задания:
> default actions should be called only if these actions are not reset in the configuration

Твой вариант с проверкой на наличие нужного метода в `this.config` рабочий, но красивее было бы использовать для задания настроек по умолчанию `defaults` (параграф Default Settings на [этой странице](https://docs.webix.com/desktop__custom_component.html#addapi) документации)

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +            this.$ready.push(this.initState);
А почему бы не сделать это в `state_setter`?

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +                webix.html.addCss($$(id).getNode(), "off");
Тут нестыковка: ты задаёшь начальный стиль, но при этом переключение стилей написано в onStateChange инициализированной кнопки. 
Нормальными будут два варианта:
- либо мы вообще не меняем стили внутри protoUI
- либо (сложнее, но лучше) меняем className внутри компонента в соответствии со state
В этом случае хорошо бы называть className по имени state с каким-то устойчивым префиксом (`"button_state_"+state`), а вот фактические стили предоставить писать пользователю 
(подразумевая, что пользователь задаёт states => знает их имена => может написать селектор)

2024-09-12 22:07 UTC, HelgaListopad commented on index.js
> +                ++config.state;
Вот тут самый главный вопрос кнопки
В задании предлагается такая конфигурация states
```js
states:{0:"Off",1:"SortAsc",2:"Sort Desc"}
```
Это объект, который пользователь задаёт сам в конфигурации кнопки. 
И раз это объект, а не массив, то мы не можем быть уверены, что ключи всегда будут последовательными числами.
Для переключения между состояниями кнопки всё ещё удобно идти по Object.entries(states), но нужно учитывать индексы, а не ключи.

<details><summary>Тут дополнение, но уже FYI</summary>

Вообще если разбираться более дотошно (здесь не будем, правки можно ограничить тем что я описала выше), то `entries` (как и `keys`, и так далее) вернёт отсортированные числовые ключи.
Т.е. вот как это будет выглядеть

```js
const a = { 3: "A", 1: "B", 0: "C" };
const b = { "d": "A", "z": "B", "m": "C" };
// отсортированы
Object.entries(a); // [0, "C"], [1, "B"], [3, "A"];
// тут остался исходный порядок
Object.entries(b); // ["d", "A"], ["z", "B"], ["m", "C"]
```

И если условный юзер в конфигурации перемешает порядок числовых ключей, то JS их всё равно отсортирует как решил нужным и только по этому порядку можно пройти, переключая states - но это уже не стоит рассматривать/решать как проблему для твоего компонента, так работает джаваскрипт :) 

Более устойчивым решением было бы изначально задавать ключи в конфигурации массивом или `Map`, но опять-таки, это уже не относится напрямую к актуальному сейчас ТЗ.

</details>

2024-09-12 22:08 UTC, HelgaListopad commented on index.js
> +                    saveaction(id)
У этой функции должен быть правильный контекст. 
Если сейчас написать
```js
    view: "customForm",
    saveAction: function () {
      this.getValues()
    },
```
То попытка вызвать getValues кинет ошибку. `this` в данном случае это не форма, а должна быть именно она.

2024-09-13 05:59 UTC, Natasha-eng commented on index.js
> +            butt.attachEvent("onItemClick", function (id) {
Только сейчас посмотрела перевод ))) Очень извиняюсь )))

2024-09-13 11:32 UTC, HelgaListopad commented on index.js
> +                ++config.state;
> И раз это объект, а не массив, то мы не можем быть уверены, что ключи всегда будут последовательными числами.

Попробуй сделать так, чтобы кнопка работала и с конфигом который у тебя есть сейчас, и с этим:
```js
const threestateButtonInstance = {
  view: "threestateButton",
  // тут ключи уже не числа
  state: "off",
  states: { "off": "Off", "asc": "Sort Asc", "desc": "Sort Desc" },
  on: {
    onStateChange: function (state) {
      const list = $$("mylist");
      if (state == "asc") {
        list.sort("#name#", "asc");
      } else if (state == "desc") {
        list.sort("#name#", "desc");
      } else if (state == "off") {
        list.sort("#id#", "asc", "int");
      }
    },
  },
}
```

2024-09-13 15:33 UTC, HelgaListopad approved these changes

2024-09-13 15:33 UTC, merged